<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.325" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2023-03-01T00:32:04" tests="1" file="cypress/e2e/logged-in.cy.js" time="1.310" failures="1">
    <testcase name="An uncaught error was detected outside of a test" time="0.274" classname="An uncaught error was detected outside of a test">
      <failure message="The following error originated from your test code, not from Cypress.

  &gt; You must provide CYPRESS_USER_EMAIL and CYPRESS_USER_PASSWORD environment variables

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure." type="Error"><![CDATA[Error: The following error originated from your test code, not from Cypress.

  > You must provide CYPRESS_USER_EMAIL and CYPRESS_USER_PASSWORD environment variables

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at ./cypress/e2e/logged-in.cy.js (webpack:///./cypress/e2e/logged-in.cy.js:5:8)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
    at 0 (http://localhost:3000/__cypress/tests?p=cypress/e2e/logged-in.cy.js:214:18)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
    at eval (webpack:///webpack/bootstrap:83:0)
    at eval (http://localhost:3000/__cypress/tests?p=cypress/e2e/logged-in.cy.js:87:10)
    at eval (<anonymous>)]]></failure>
    </testcase>
  </testsuite>
</testsuites>